sonar.organization=graphffy
sonar.projectKey=graphffy_gym-tracker-v.1
sonar.projectName=gym-tracker

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.inclusions=src/main/java/com/gym/gymtracker/service/**

sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8

# Coverage is evaluated only for the service layer.
sonar.coverage.inclusions=src/main/java/com/gym/gymtracker/service/**
