sonar.organization=graphffy
sonar.projectKey=graphffy_gym-tracker-v.1
sonar.projectName=gym-tracker

sonar.sources=src/main/java/com/gym/gymtracker/service
sonar.tests=src/test/java
sonar.exclusions=src/main/java/com/gym/gymtracker/controller/**,src/main/java/com/gym/gymtracker/model/**,src/main/java/com/gym/gymtracker/mapper/**,src/main/java/com/gym/gymtracker/dto/**,src/main/java/com/gym/gymtracker/config/**,src/main/java/com/gym/gymtracker/exception/**,src/main/java/com/gym/gymtracker/aspect/**,src/main/java/com/gym/gymtracker/repository/**,src/main/java/com/gym/gymtracker/GymTrackerApplication.java

sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8

# Only service layer is analyzed and covered.
sonar.coverage.inclusions=src/main/java/com/gym/gymtracker/service/**
